data:extend({
  {type = "item", name = "tungsten-ore",
	icon = "__BaseMod__/graphics/icons/ores/tungsten-ore.png",
	flags = { "goes-to-main-inventory" },
	stack_size = 200,
  },
  {type = "item", name = "sodium-tungstate",
	icon = "__BaseMod__/graphics/icons/sodium-tungstate.png",
	flags = { "goes-to-main-inventory" },
	stack_size = 200,
  },
  {type = "item", name = "ammonium-tungstate",
	icon = "__BaseMod__/graphics/icons/ammonium-tungstate.png",
	flags = { "goes-to-main-inventory" },
	stack_size = 200,
  },
  {type = "item", name = "tungsten-powder",
	icon = "__BaseMod__/graphics/icons/tungsten-powder.png",
	flags = { "goes-to-main-inventory" },
	stack_size = 200,
  },
  
  { type = "recipe", name = "tungsten-processing",
	icon = "__BaseMod__/graphics/icons/sodium-tungstate.png",
	category = "chemistry",
	enabled = false,
	energy_required = 2.0,
	ingredients = {{"tungsten-ore",5},{"sodium-hydroxide",1},{type="fluid",name="water",amount=2}},
	results = {{type="item",name="sodium-tungstate",amount=5}},
	subgroup = "ci-tungsten",
	order = "a",
  },
  { type = "recipe", name = "tungsten-processing-2",
	icon = "__BaseMod__/graphics/icons/ammonium-tungstate.png",
	category = "chemistry",
	enabled = false,
	energy_required = 2.0,
	ingredients = {{"sodium-tungstate",3},{type="fluid",name="ammonia",amount=1},{type="fluid",name="water",amount=2}},
	results = {{type="item",name="ammonium-tungstate",amount=3}},
	subgroup = "ci-tungsten",
	order = "b",
  },
  { type = "recipe", name = "tungsten-processing-3",
	icon = "__BaseMod__/graphics/icons/tungsten-powder.png",
	category = "chemistry",
	enabled = false,
	energy_required = 2.0,
	ingredients = {{"ammonium-tungstate",1},{type="fluid",name="hydrogen",amount=1}},
	results = {{type="item",name="tungsten-powder",amount=2}},
	subgroup = "ci-tungsten",
	order = "c",
  },

})