data:extend({
{ type = "recipe", name = "small-blast-furnace",
    category = "crafting",
	energy_required = 5,
	icon = "__CartmenIndustries__/graphics/icons/b_furnace_small_icon.png",
	ingredients = {
	{type="item",name="stone-brick",amount=5}
	},
	results = {
	{type="item",name="small-blast-furnace",amount=1}
	},
	subgroup = "ci-tech",
	order = "a2",
  },
  
  { type = "recipe", name = "casting-facility",
    category = "crafting",
	energy_required = 5,
	icon = "__CartmenIndustries__/graphics/icons/cooler.png",
	ingredients = {
	{type="item",name="stone-brick",amount=6},
	{type="item",name="iron-plate",amount=4}
	},
	results = {
	{type="item",name="casting-facility",amount=1}
	},
	subgroup = "ci-tech",
	order = "c",
  },
  
  { type = "recipe", name = "mill",
    category = "crafting",
	energy_required = 5,
	icon = "__CartmenIndustries__/graphics/icons/crusher-icon.png",
	ingredients = {
	{type="item",name="iron-gear-wheel",amount=6},
	{type="item",name="stone-brick",amount=6},
	{type="item",name="iron-plate",amount=10}
	},
	results = {
	{type="item",name="mill",amount=1}
	},
	subgroup = "ci-tech",
	order = "b1",
  },
  { type = "recipe", name = "mill-2",
    category = "crafting",
	energy_required = 5,
	icon = "__CartmenIndustries__/graphics/icons/crusher-icon.png",
	ingredients = {
	{type="item",name="steel-plate",amount=5},
	{type="item",name="iron-gear-wheel",amount=10},
	{type="item",name="electronic-circuit",amount=4},
	{type="item",name="mill",amount=1}
	},
	results = {
	{type="item",name="mill-2",amount=1}
	},
	subgroup = "ci-tech",
	order = "b2",
  },
  
  { type = "recipe", name = "flotation-cell",
    category = "crafting",
	energy_required = 10,
	icon = "__base__/graphics/icons/storage-tank.png",
	ingredients = {
	{type="item",name="iron-plate",amount=20},
	{type="item",name="steel-plate",amount=10},
	{type="item",name="electronic-circuit",amount=5}
	},
	results = {
	{type="item",name="flotation-cell",amount=1}
	},
	subgroup = "ci-tech",
	order = "d",
  },

  { type = "recipe", name = "iron-crushing",
	icon = "__CartmenIndustries__/graphics/icons/ores/crushed-iron-ore.png",
	category = "mill",
	energy_required = 2.0,
	ingredients = {{"iron-ore",1}},
	results = {{type="item",name="crushed-iron-ore",amount=2}},
	subgroup = "ci-iron",
	order = "a",
  },
  { type = "recipe", name = "iron-casting",
	icon = "__base__/graphics/icons/iron-plate.png",
	category = "blast-furnace",
	energy_required = 3.5,
	ingredients = {{"crushed-iron-ore",2}},
	results = {{type="item",name="iron-plate",amount=3}},
	subgroup = "ci-iron",
	order = "b",
  },
  
  { type = "recipe", name = "copper-crushing",
	icon = "__CartmenIndustries__/graphics/icons/ores/crushed-copper-ore.png",
	category = "mill",
	energy_required = 2.0,
	ingredients = {{"copper-ore",1}},
	results = {{type="item",name="crushed-copper-ore",amount=2}},
	subgroup = "ci-copper",
	order = "c",
  },
  { type = "recipe", name = "copper-flotation",
	icon = "__CartmenIndustries__/graphics/icons/ores/copper-concentrate.png",
	category = "flotation",
	energy_required = 10,
	ingredients = {{"crushed-copper-ore",10}},
	results = {{type="item",name="copper-concentrate",amount=10}},
	subgroup = "ci-copper",
	order = "d",
  },
  { type = "recipe", name = "copper-smelting-2",
	icon = "__CartmenIndustries__/graphics/icons/fluids/copper-matte.png",
	category = "blast-furnace",
	energy_required = 10,
	ingredients = {{"copper-concentrate",10},{"stone",2}},
	results = {{type="fluid",name="copper-matte",amount=100},{type="fluid",name="sulfur-dioxide",amount=25}},
	subgroup = "ci-copper",
	order = "e",
  },
  { type = "recipe", name = "copper-smelting-3",
	icon = "__CartmenIndustries__/graphics/icons/fluids/copper-blister.png",
	category = "blast-furnace",
	energy_required = 10,
	ingredients = {{type="fluid",name="copper-matte",amount=100},{"stone",2}},
	results = {{type="fluid",name="copper-blister",amount=100},{type="fluid",name="sulfur-dioxide",amount=15}},
	subgroup = "ci-copper",
	order = "f1",
  },
  { type = "recipe", name = "copper-casting-2",
	icon = "__base__/graphics/icons/copper-plate.png",
	category = "casting",
	energy_required = 2.0,
	ingredients = {{type="fluid",name="copper-blister",amount=20},{"stone",1}},
	results = {{type="item",name="copper-plate",amount=3}},
	subgroup = "ci-copper",
	order = "f2",
  },
  { type = "recipe", name = "copper-refining",
	icon = "__CartmenIndustries__/graphics/icons/copper-anode.png",
	category = "casting",
	energy_required = 10,
	ingredients = {{type="fluid",name="copper-blister",amount=50}},
	results = {{type="item",name="copper-anode",amount=10}},
	subgroup = "ci-copper",
	order = "g",
  },
  { type = "recipe", name = "copper-electro-refining",
	icon = "__base__/graphics/icons/copper-plate.png",
	category = "chemistry",
	energy_required = 10,
	ingredients = {{type="item",name="copper-anode",amount=20},{type="fluid",name="sulfuric-acid",amount=40}},
	results = {{type="item",name="copper-plate",amount=20}},
	subgroup = "ci-copper",
	order = "h",
  },
  { type = "recipe", name = "sulfur-dioxide-processing",
    icon = "__base__/graphics/icons/fluid/sulfuric-acid.png",
	category = "chemistry",
	energy_required = 1,
	ingredients = {{type="fluid",name="sulfur-dioxide",amount=20},{type="fluid",name="water",amount=20}},
	results = {{type="fluid",name="sulfuric-acid",amount=20}},
	subgroup = "ci-chemicals",
	order = "a",
  },
})