data:extend({
  --Quartz
  { type = "recipe", name = "quartz-processing",
	icon = "__CartmenIndustries__/graphics/icons/ores/quartz.png",
	category = "mineral",
	enabled = false,
	energy_required = 1,
	ingredients = {{"stone",1}},
	results = {{type="item",name="quartz-ore",amount=1}},
	subgroup = "ci-ore-processing",
	order = "a-b[quartz]",
  },
  { type = "recipe", name = "silicon-processing",
	icon = "__CartmenIndustries__/graphics/icons/fluids/liquid-silicon.png",
	category = "blast-furnace",
	enabled = false,
	energy_required = 2.0,
	ingredients = {{"quartz-ore",4}},
	results = {{type="fluid",name="liquid-silicon",amount=10}},
	subgroup = "ci-silicon",
	order = "a",
  },
  { type = "recipe", name = "silicon-casting",
	icon = "__CartmenIndustries__/graphics/icons/silicon-plate.png",
	category = "casting",
	enabled = false,
	energy_required = 1.5,
	ingredients = {{type="fluid",name="liquid-silicon",amount=10}},
	results = {{"silicon-plate",1}},
	subgroup = "ci-silicon",
	order = "b",
  },
  { type = "recipe", name = "silicon-boule",
	icon = "__CartmenIndustries__/graphics/icons/silicon-boule.png",
	category = "casting",
	enabled = false,
	energy_required = 6,
	ingredients = {{type="fluid",name="liquid-silicon",amount=100}},
	results = {{"silicon-boule",1}},
	subgroup = "ci-silicon",
	order = "c",
  },
  { type = "recipe", name = "silicon-wafer",
	icon = "__CartmenIndustries__/graphics/icons/silicon-wafer.png",
	category = "advanced-crafting",
	enabled = false,
	energy_required = 20,
	ingredients = {{type="item",name="silicon-boule",amount=1}},
	results = {{"silicon-wafer",20}},
	subgroup = "ci-silicon",
	order = "d",
  },

})