data:extend({

  { type = "item", name = "crude-circuit",
	icon = "__CartmenIndustries__/graphics/icons/crude-circuit.png",
	flags = { "goes-to-main-inventory" },
	order = "a-a",
	stack_size = 50,
  },
  
  { type = "item", name = "solder",
	icon = "__CartmenIndustries__/graphics/icons/solder.png",
	flags = { "goes-to-main-inventory" },
	order = "a-a",
	stack_size = 200,
  },
  
  { type = "item", name = "crude-circuit-board",
	icon = "__CartmenIndustries__/graphics/icons/crude-circuit-board.png",
	flags = { "goes-to-main-inventory" },
	order = "a-a",
	stack_size = 25,
  },
  
  { type = "item", name = "crude-transistor",
	icon = "__CartmenIndustries__/graphics/icons/crude-transistor.png",
	flags = { "goes-to-main-inventory" },
	order = "a-a",
	stack_size = 100,
  },
  
  { type = "item", name = "standard-circuit-board",
	icon = "__CartmenIndustries__/graphics/icons/standard-circuit-board.png",
	flags = { "goes-to-main-inventory" },
	order = "b2",
	stack_size = 50,
  },
  
  { type = "item", name = "transistor",
	icon = "__CartmenIndustries__/graphics/icons/transistor.png",
	flags = { "goes-to-main-inventory" },
	order = "b2",
	stack_size = 200,
  },
  
  { type = "item", name = "resistor",
	icon = "__CartmenIndustries__/graphics/icons/resistor.png",
	flags = { "goes-to-main-inventory" },
	order = "b2",
	stack_size = 200,
  },
  
  { type = "item", name = "integrated-circuit",
	icon = "__CartmenIndustries__/graphics/icons/chip.png",
	flags = { "goes-to-main-inventory" },
	order = "b2",
	stack_size = 200,
  },
  
  { type = "item", name = "processing-core",
	icon = "__CartmenIndustries__/graphics/icons/processing-core.png",
	flags = { "goes-to-main-inventory" },
	order = "b2",
	stack_size = 50,
  },
 
})