data:extend({
  { type = "item", name = "small-blast-furnace",
	icon = "__CartmenIndustries__/graphics/icons/b_furnace_small_icon.png",
	flags = { "goes-to-quickbar" },
	subgroup = "ci-tech",
	order = "m-a[small-blast-furnace]",
	stack_size = 50,
	place_result = "small-blast-furnace",
  },
  { type = "item", name = "casting-facility",
	icon = "__CartmenIndustries__/graphics/icons/cooler.png",
	flags = { "goes-to-quickbar" },
	subgroup = "ci-tech",
	order = "m-a[cooler]",
	stack_size = 50,
	place_result = "casting-facility",
  },
  { type = "item", name = "mill",
	icon = "__CartmenIndustries__/graphics/icons/crusher-icon.png",
	flags = { "goes-to-quickbar" },
	subgroup = "ci-tech",
	order = "m-a[mill]",
	stack_size = 50,
	place_result = "mill",
  },
  { type = "item", name = "mill-2",
	icon = "__CartmenIndustries__/graphics/icons/crusher-icon.png",
	flags = { "goes-to-quickbar" },
	subgroup = "ci-tech",
	order = "m-a[mill-2]",
	stack_size = 50,
	place_result = "mill-2",
  },
  { type = "item", name = "flotation-cell",
	icon = "__base__/graphics/icons/storage-tank.png",
	flags = { "goes-to-quickbar" },
	subgroup = "ci-tech",
	order = "m-a[flotation-cell]",
	stack_size = 25,
	place_result = "flotation-cell",
  },
  
  { type = "fluid", name = "copper-matte",
    default_temperature = 1200,
	max_temperature = 1200,
	heat_capacity = "0KJ",
	base_color = {r= 204, g= 102, b= 0},
	flow_color = {r= 204, g= 102, b= 0},
	icon = "__CartmenIndustries__/graphics/icons/fluids/copper-matte.png",
	subgroup = "ci-copper",
	order = "c",
	pressure_to_speed_ratio = 0.4,
	flow_to_energy_ratio = 0.59,
  },
  { type = "fluid", name = "copper-blister",
    default_temperature = 1200,
	max_temperature = 1200,
	heat_capacity = "0KJ",
	base_color = {r= 204, g= 102, b= 0},
	flow_color = {r= 204, g= 102, b= 0},
	icon = "__CartmenIndustries__/graphics/icons/fluids/copper-blister.png",
	subgroup = "ci-copper",
	order = "c",
	pressure_to_speed_ratio = 0.4,
	flow_to_energy_ratio = 0.59,
  },
  { type = "fluid", name = "sulfur-dioxide",
    default_temperature = 1200,
	max_temperature = 1200,
	heat_capacity = "0KJ",
	base_color = {r=0, g=0.7, b=0.2},
    flow_color = {r=0.5, g=0.5, b=0.5},
	icon = "__CartmenIndustries__/graphics/icons/fluids/sulfur-dioxide.png",
	subgroup = "ci-chemicals",
	order = "a",
	pressure_to_speed_ratio = 0.4,
	flow_to_energy_ratio = 0.59,
  },
  
  {type = "item", name = "crushed-copper-ore",
	icon = "__CartmenIndustries__/graphics/icons/ores/crushed-copper-ore.png",
	flags = { "goes-to-main-inventory" },
	order = "a-o[copper]",
	stack_size = 200,
  },
  {type = "item", name = "copper-concentrate",
	icon = "__CartmenIndustries__/graphics/icons/ores/copper-concentrate.png",
	flags = { "goes-to-main-inventory" },
	order = "a-o[copper]",
	stack_size = 200,
  },
  {type = "item", name = "crushed-iron-ore",
	icon = "__CartmenIndustries__/graphics/icons/ores/crushed-iron-ore.png",
	flags = { "goes-to-main-inventory" },
	order = "a-o[iron]",
	stack_size = 200,
  },
  {type = "item", name = "copper-anode",
	icon = "__CartmenIndustries__/graphics/icons/copper-anode.png",
	flags = { "goes-to-main-inventory" },
	order = "a-p[copper]",
	stack_size = 200,
  },
})