data:extend({
  {type = "item", name = "lead-ore",
	icon = "__CartmenIndustries__/graphics/icons/ores/lead-ore.png",
	flags = { "goes-to-main-inventory" },
	order = "a-o[lead]",
	stack_size = 200,
  },
  {type = "item", name = "crushed-lead-ore",
	icon = "__CartmenIndustries__/graphics/icons/ores/crushed-lead-ore.png",
	flags = { "goes-to-main-inventory" },
	order = "a-o[lead]",
	stack_size = 200,
  },
  {type = "item", name = "lead-concentrate",
	icon = "__CartmenIndustries__/graphics/icons/ores/lead-concentrate.png",
	flags = { "goes-to-main-inventory" },
	order = "a-o[lead]",
	stack_size = 200,
  },
  {type = "item", name = "lead-sinter",
	icon = "__CartmenIndustries__/graphics/icons/ores/lead-sinter.png",
	flags = { "goes-to-main-inventory" },
	order = "a-o[lead]",
	stack_size = 200,
  },
  
  {type = "item", name = "tin-ore",
	icon = "__CartmenIndustries__/graphics/icons/ores/tin-ore.png",
	flags = { "goes-to-main-inventory" },
	order = "a-o[tin]",
	stack_size = 200,
  },
  {type = "item", name = "crushed-tin-ore",
	icon = "__CartmenIndustries__/graphics/icons/ores/crushed-tin-ore.png",
	flags = { "goes-to-main-inventory" },
	order = "a-o[tin]",
	stack_size = 200,
  },
  {type = "item", name = "tin-concentrate",
	icon = "__CartmenIndustries__/graphics/icons/ores/tin-concentrate.png",
	flags = { "goes-to-main-inventory" },
	order = "a-o[tin]",
	stack_size = 200,
  },
  
  {type = "item", name = "silver-ore",
	icon = "__CartmenIndustries__/graphics/icons/ores/silver-ore.png",
	flags = { "goes-to-main-inventory" },
	order = "a-o[silver]",
	stack_size = 200,
  },
  
  {type = "item", name = "gold-ore",
	icon = "__CartmenIndustries__/graphics/icons/ores/gold-ore.png",
	flags = { "goes-to-main-inventory" },
	order = "a-o[gold]",
	stack_size = 200,
  },
  
  {type = "item", name = "crushed-copper-ore",
	icon = "__CartmenIndustries__/graphics/icons/ores/crushed-copper-ore.png",
	flags = { "goes-to-main-inventory" },
	order = "a-o[copper]",
	stack_size = 200,
  },
  {type = "item", name = "copper-concentrate",
	icon = "__CartmenIndustries__/graphics/icons/ores/copper-concentrate.png",
	flags = { "goes-to-main-inventory" },
	order = "a-o[copper]",
	stack_size = 200,
  },
  
  {type = "item", name = "crushed-iron-ore",
	icon = "__CartmenIndustries__/graphics/icons/ores/crushed-iron-ore.png",
	flags = { "goes-to-main-inventory" },
	order = "a-o[iron]",
	stack_size = 200,
  },
  
  {type = "item", name = "nickel-ore",
	icon = "__CartmenIndustries__/graphics/icons/ores/nickel-ore.png",
	flags = { "goes-to-main-inventory" },
	order = "a-o[nickel]",
	stack_size = 200,
  },
  
  {type = "item", name = "zinc-ore",
	icon = "__CartmenIndustries__/graphics/icons/ores/zinc-ore.png",
	flags = { "goes-to-main-inventory" },
	order = "a-o[zinc]",
	stack_size = 200,
  },
  {type = "item", name = "crushed-zinc-ore",
	icon = "__CartmenIndustries__/graphics/icons/ores/crushed-zinc-ore.png",
	flags = { "goes-to-main-inventory" },
	order = "a-o[zinc]",
	stack_size = 200,
  },
  {type = "item", name = "zinc-concentrate",
	icon = "__CartmenIndustries__/graphics/icons/ores/zinc-concentrate.png",
	flags = { "goes-to-main-inventory" },
	order = "a-o[zinc]",
	stack_size = 200,
  },
  {type = "item", name = "zinc-sinter",
	icon = "__CartmenIndustries__/graphics/icons/ores/zinc-sinter.png",
	flags = { "goes-to-main-inventory" },
	order = "a-o[zinc]",
	stack_size = 200,
  },
  
  {type = "item", name = "quartz-ore",
	icon = "__CartmenIndustries__/graphics/icons/ores/quartz.png",
	flags = { "goes-to-main-inventory" },
	order = "a-o[quartz]",
	stack_size = 200,
  },
  
  {type = "item", name = "salt",
	icon = "__CartmenIndustries__/graphics/icons/ores/salt.png",
	flags = { "goes-to-main-inventory" },
	order = "a-o[salt]",
	stack_size = 200,
  },
  
  {type = "item", name = "titanium-ore",
	icon = "__CartmenIndustries__/graphics/icons/ores/titanium-ore.png",
	flags = { "goes-to-main-inventory" },
	order = "a-o[titanium]",
	stack_size = 200,
  },

  {type = "item", name = "tungsten-ore",
	icon = "__CartmenIndustries__/graphics/icons/ores/tungsten-ore.png",
	flags = { "goes-to-main-inventory" },
	order = "a-o[tungsten]",
	stack_size = 200,
  },
  
  {type = "item", name = "limestone",
	icon = "__CartmenIndustries__/graphics/icons/ores/limestone.png",
	flags = { "goes-to-main-inventory" },
	order = "a-o[limestone]",
	stack_size = 200,
  },
  {type = "item", name = "crushed-limestone",
	icon = "__CartmenIndustries__/graphics/icons/ores/crushed-limestone.png",
	flags = { "goes-to-main-inventory" },
	order = "a-o[limestone]",
	stack_size = 200,
  },
  {type = "item", name = "calcinated-limestone",
	icon = "__CartmenIndustries__/graphics/icons/ores/calcinated-limestone.png",
	flags = { "goes-to-main-inventory" },
	order = "a-o[limestone]",
	stack_size = 200,
  },

  })