data:extend({
  {type = "item", name = "lead-plate",
	icon = "__CartmenIndustries__/graphics/icons/lead-plate.png",
	flags = { "goes-to-main-inventory" },
	order = "a-p[lead]",
	stack_size = 200,
  },
  
  {type = "item", name = "tin-plate",
	icon = "__CartmenIndustries__/graphics/icons/tin-plate.png",
	flags = { "goes-to-main-inventory" },
	order = "a-p[tin]",
	stack_size = 200,
  },
  
  {type = "item", name = "copper-anode",
	icon = "__CartmenIndustries__/graphics/icons/copper-anode.png",
	flags = { "goes-to-main-inventory" },
	order = "a-p[copper]",
	stack_size = 200,
  },
  
  {type = "item", name = "zinc-plate",
	icon = "__CartmenIndustries__/graphics/icons/zinc-plate.png",
	flags = { "goes-to-main-inventory" },
	order = "a-p[zinc]",
	stack_size = 200,
  },
  
  {type = "item", name = "silver-plate",
	icon = "__CartmenIndustries__/graphics/icons/silver-plate.png",
	flags = { "goes-to-main-inventory" },
	order = "a-p[silver]",
	stack_size = 200,
  },
  
  {type = "item", name = "gold-plate",
	icon = "__CartmenIndustries__/graphics/icons/gold-plate.png",
	flags = { "goes-to-main-inventory" },
	order = "a-p[gold]",
	stack_size = 200,
  },
  
  {type = "item", name = "titanium-sponge",
	icon = "__CartmenIndustries__/graphics/icons/ores/titanium-sponge.png",
	flags = { "goes-to-main-inventory" },
	order = "a-p[titanium]",
	stack_size = 200,
  },
  
  {type = "item", name = "titanium-plate",
	icon = "__CartmenIndustries__/graphics/icons/titanium-plate.png",
	flags = { "goes-to-main-inventory" },
	order = "a-p[titanium]",
	stack_size = 200,
  },
})