data:extend({
  { type = "fluid", name = "photoresist",
    default_temperature = 15,
    heat_capacity = "0KJ",
    base_color = {r=0.4, g=0, b=0.4},
    flow_color = {r=0.5, g=0.5, b=0.5},
    max_temperature = 100,
    icon = "__CartmenIndustries__/graphics/icons/fluids/photoresist.png",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "a[fluid]-e[petroleum-gas]"
  },
  
  { type = "fluid", name = "epoxy",
    default_temperature = 15,
    heat_capacity = "0KJ",
    base_color = {r=0.4, g=0, b=0.4},
    flow_color = {r=0.5, g=0.5, b=0.5},
    max_temperature = 100,
    icon = "__CartmenIndustries__/graphics/icons/fluids/epoxy.png",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "a[fluid]-e[petroleum-gas]"
  },
  
  { type = "fluid", name = "bisphenol",
    default_temperature = 15,
    heat_capacity = "0KJ",
    base_color = {r=0.4, g=0, b=0.4},
    flow_color = {r=0.5, g=0.5, b=0.5},
    max_temperature = 100,
    icon = "__CartmenIndustries__/graphics/icons/fluids/bisphenol.png",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "a[fluid]-e[petroleum-gas]"
  },
  
  { type = "fluid", name = "epichlorohydrin",
    default_temperature = 15,
    heat_capacity = "0KJ",
    base_color = {r=0.4, g=0, b=0.4},
    flow_color = {r=0.5, g=0.5, b=0.5},
    max_temperature = 100,
    icon = "__CartmenIndustries__/graphics/icons/fluids/epichlorohydrin.png",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "a[fluid]-e[petroleum-gas]"
  },
  
  { type = "fluid", name = "allyl-chloride",
    default_temperature = 15,
    heat_capacity = "0KJ",
    base_color = {r=0.4, g=0, b=0.4},
    flow_color = {r=0.5, g=0.5, b=0.5},
    max_temperature = 100,
    icon = "__CartmenIndustries__/graphics/icons/fluids/allyl-chloride.png",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "a[fluid]-e[petroleum-gas]"
  },
  
  { type = "fluid", name = "hypochlorous-acid",
    default_temperature = 15,
    heat_capacity = "0KJ",
    base_color = {r=0.4, g=0, b=0.4},
    flow_color = {r=0.5, g=0.5, b=0.5},
    max_temperature = 100,
    icon = "__CartmenIndustries__/graphics/icons/fluids/hypochlorous-acid.png",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "a[fluid]-e[petroleum-gas]"
  },
  
  { type = "fluid", name = "propene",
    default_temperature = 15,
    heat_capacity = "0KJ",
    base_color = {r=0.4, g=0, b=0.4},
    flow_color = {r=0.5, g=0.5, b=0.5},
    max_temperature = 100,
    icon = "__CartmenIndustries__/graphics/icons/fluids/propene.png",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "a[fluid]-e[petroleum-gas]"
  },
  
  { type = "fluid", name = "hydrogen",
    default_temperature = 15,
    heat_capacity = "0KJ",
    base_color = {r=0.4, g=0, b=0.4},
    flow_color = {r=0.5, g=0.5, b=0.5},
    max_temperature = 100,
    icon = "__CartmenIndustries__/graphics/icons/fluids/hydrogen.png",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "a[fluid]-e[petroleum-gas]"
  },
  
  { type = "fluid", name = "chlorine",
    default_temperature = 15,
    heat_capacity = "0KJ",
    base_color = {r=0.4, g=0, b=0.4},
    flow_color = {r=0.5, g=0.5, b=0.5},
    max_temperature = 100,
    icon = "__CartmenIndustries__/graphics/icons/fluids/chlorine.png",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "a[fluid]-e[petroleum-gas]"
  },
  
  { type = "fluid", name = "hydrogen-chloride",
    default_temperature = 15,
    heat_capacity = "0KJ",
    base_color = {r=0.4, g=0, b=0.4},
    flow_color = {r=0.5, g=0.5, b=0.5},
    max_temperature = 100,
    icon = "__CartmenIndustries__/graphics/icons/fluids/hydrogen-chloride.png",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "a[fluid]-e[petroleum-gas]"
  },
  
  { type = "fluid", name = "hydrochloric-acid",
    default_temperature = 15,
    heat_capacity = "0KJ",
    base_color = {r=0.4, g=0, b=0.4},
    flow_color = {r=0.5, g=0.5, b=0.5},
    max_temperature = 100,
    icon = "__CartmenIndustries__/graphics/icons/fluids/hydrochloric-acid.png",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "a[fluid]-e[petroleum-gas]"
  },
  
  { type = "fluid", name = "ammonia",
    default_temperature = 15,
    heat_capacity = "0KJ",
    base_color = {r=0.4, g=0, b=0.4},
    flow_color = {r=0.5, g=0.5, b=0.5},
    max_temperature = 100,
    icon = "__CartmenIndustries__/graphics/icons/fluids/ammonia.png",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "a[fluid]-e[petroleum-gas]"
  },
  
  { type = "fluid", name = "nickel-carbonyl",
    default_temperature = 55,
    heat_capacity = "0KJ",
    base_color = {r=0.4, g=0, b=0.4},
    flow_color = {r=0.5, g=0.5, b=0.5},
    max_temperature = 100,
    icon = "__CartmenIndustries__/graphics/icons/fluids/nickel-carbonyl.png",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "a[fluid]-e[petroleum-gas]"
  },
  
  { type = "fluid", name = "carbon-monoxide",
    default_temperature = 15,
    heat_capacity = "0KJ",
    base_color = {r=0.4, g=0, b=0.4},
    flow_color = {r=0.5, g=0.5, b=0.5},
    max_temperature = 100,
    icon = "__CartmenIndustries__/graphics/icons/fluids/carbon-monoxide.png",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "a[fluid]-e[petroleum-gas]"
  },
  
  {
    type = "fluid",
    name = "butadiene",
    default_temperature = 25,
    heat_capacity = "0KJ",
    base_color = {r=176, g=176, b=131},
    flow_color = {r=176, g=176, b=131},
    max_temperature = 100,
    icon = "__CartmenIndustries__/graphics/icons/fluids/butadiene.png",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "a[fluid]-c[butadiene]"
  },
})